const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.BinaryData,
		C3.Plugins.Button,
		C3.Plugins.Camera3D,
		C3.Plugins.Json,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Plugins.Date,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Shape3D,
		C3.Plugins.Mikal_3DObject,
		C3.Behaviors.EightDir,
		C3.Behaviors.Car,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Mikal_3DObject.Cnds.OnLoaded,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Mikal_3DObject.Acts.DeleteMaterial,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Mikal_3DObject.Acts.LoadMaterial,
		C3.ScriptsInEvents.Initevt_Event82_Act2,
		C3.ScriptsInEvents.Initevt_Event82_Act4,
		C3.ScriptsInEvents.Initevt_Event82_Act9,
		C3.ScriptsInEvents.Initevt_Event82_Act11,
		C3.ScriptsInEvents.Initevt_Event82_Act13,
		C3.ScriptsInEvents.Initevt_Event82_Act16,
		C3.ScriptsInEvents.Initevt_Event82_Act18,
		C3.ScriptsInEvents.Initevt_Event82_Act21,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Mikal_3DObject.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationBlend,
		C3.Plugins.Mikal_3DObject.Acts.PlayAnimation,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.ScriptsInEvents.Snippetsevt_Event130_Act1,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Mikal_3DObject.Acts.MoveToLayer,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.Difference,
		C3.Plugins.Date.Exps.GetDay,
		C3.ScriptsInEvents.Snippetsevt_Event215_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event217_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event219_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event221_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event223_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event225_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event227_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event229_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event231_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event233_Act1,
		C3.ScriptsInEvents.Snippetsevt_Event235_Act1,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Date.Exps.ToTotalHours,
		C3.Plugins.Date.Exps.ToTimerHours,
		C3.Plugins.Date.Exps.ToTimerMinutes,
		C3.Plugins.Date.Exps.ToTimerSeconds,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationRate,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.LocalStorage.Cnds.OnItemRemoved,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetVAlign,
		C3.Plugins.Text.Acts.SetHAlign,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.wallclocktime,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.Browser.Exps.Domain,
		C3.ScriptsInEvents.Adevt_Event12_Act3,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Mikal_3DObject.Acts.SetMeshMaterial,
		C3.Plugins.Mikal_3DObject.Cnds.OnAnimationFinished,
		C3.Plugins.Mikal_3DObject.Acts.EnableNode,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Mikal_3DObject.Acts.SetInstanceVar,
		C3.Plugins.Mikal_3DObject.Exps.X,
		C3.Plugins.Mikal_3DObject.Exps.Y,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.ZMoveToObject,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Mikal_3DObject.Cnds.CompareInstanceVar,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationSpeed,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.Text.Exps.LayerName,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Exps.PickedCount,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mikal_3DObject.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Mikal_3DObject.Exps.NodePointPosition,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.ScriptsInEvents.Akcijaps3evt_Event8_Act2,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.CompareInstanceVar,
		C3.Plugins.Button.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Mikal_3DObject.Cnds.CompareY,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Mikal_3DObject.Acts.SetX,
		C3.Plugins.Shape3D.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.rgb,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.ScriptsInEvents.Akcijaps3evt_Event105_Act1,
		C3.Plugins.Mikal_3DObject.Cnds.OnAnimationNameFinished,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.System.Acts.Signal,
		C3.ScriptsInEvents.Akcijaps3evt_Event176_Act4,
		C3.Plugins.Mikal_3DObject.Acts.SetEffectEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsActive,
		C3.Behaviors.lunarray_LiteTween.Exps.Value,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Shape3D.Cnds.CompareWidth,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Shape3D.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Camera3D.Exps.LayerToLayerX,
		C3.Plugins.Shape3D.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Sin.Exps.Period,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Cnds.CompareX,
		C3.Plugins.Mikal_3DObject.Acts.StopAnimation,
		C3.Plugins.Mikal_3DObject.Acts.SetXScale,
		C3.Plugins.Mikal_3DObject.Exps.XScale,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Mikal_3DObject.Cnds.IsPlaying,
		C3.Plugins.Mikal_3DObject.Exps.CurrentAnimationFrame,
		C3.Plugins.Mikal_3DObject.Acts.SetZElevation0,
		C3.Plugins.Mikal_3DObject.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.ScriptsInEvents.Akcijaps3evt_Event381_Act1,
		C3.ScriptsInEvents.Akcijaps3evt_Event382_Act2,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.Opacity,
		C3.Plugins.Shape3D.Acts.SetTowardPosition,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.Shape3D.Cnds.CompareY,
		C3.Plugins.Shape3D.Acts.SetEffectEnabled,
		C3.Behaviors.lunarray_LiteTween.Acts.SetValue,
		C3.ScriptsInEvents.Akcijaps3evt_Event397_Act1,
		C3.ScriptsInEvents.Akcijaps3evt_Event424_Act1,
		C3.Plugins.Mikal_3DObject.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mikal_3DObject.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetWave,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.SetFaceImage,
		C3.Plugins.Shape3D.Exps.LayerName,
		C3.Plugins.Shape3D.Acts.SetFaceVisible,
		C3.Plugins.Shape3D.Acts.SetY,
		C3.Plugins.Shape3D.Acts.SetHeight,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Mikal_3DObject.Acts.SetOpacity,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Shape3D.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.ScriptsInEvents.Akcijaps3evt_Event538_Act1
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{BinaryData: 0},
	{ButtonPS3: 0},
	{"3DCamera": 0},
	{JSON: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Touch: 0},
	{AJAX: 0},
	{Keyboard: 0},
	{Date: 0},
	{Fade: 0},
	{SVGPicture: 0},
	{id: 0},
	{Pin: 0},
	{teamPickButton: 0},
	{zvezdicazalogo: 0},
	{teamID: 0},
	{Sine: 0},
	{teamLogo: 0},
	{strength: 0},
	{PrevLevel: 0},
	{NextLevel: 0},
	{vrsta: 0},
	{restartujemLejaut: 0},
	{TestDugme: 0},
	{class: 0},
	{picked: 0},
	{subclass: 0},
	{res: 0},
	{touchEnabled: 0},
	{Flash: 0},
	{button: 0},
	{tier: 0},
	{levelButton: 0},
	{myLogo: 0},
	{partnerLogo: 0},
	{colorID: 0},
	{boja: 0},
	{teamColor: 0},
	{krila_buttonLevel: 0},
	{podloga_za_broj: 0},
	{cupBranchPivot: 0},
	{originalWidth: 0},
	{originalHeight: 0},
	{round: 0},
	{teamLogoCupBranch: 0},
	{cupTree: 0},
	{kup: 0},
	{kup2: 0},
	{lovor: 0},
	{Rotate: 0},
	{teamLogoZraci: 0},
	{level: 0},
	{subId: 0},
	{levelButtonStarMap: 0},
	{levelIntroImage: 0},
	{thumbFrame: 0},
	{page_indicator: 0},
	{type: 0},
	{temp: 0},
	{Tween: 0},
	{uniThumb: 0},
	{prevTouchY: 0},
	{curTouchY: 0},
	{DiffY: 0},
	{upperLimitY: 0},
	{lowerLimitY: 0},
	{mouseRollDeltaY: 0},
	{prevTouchX: 0},
	{curTouchX: 0},
	{DiffX: 0},
	{upperLimitX: 0},
	{lowerLimitX: 0},
	{mouseRollDeltaX: 0},
	{currentPage: 0},
	{ScrollTo: 0},
	{DragDrop: 0},
	{MoveTo: 0},
	{scroller: 0},
	{maskAchievements: 0},
	{gemParticles: 0},
	{pausePanel: 0},
	{startX: 0},
	{startY: 0},
	{isOnScreen: 0},
	{uniPanel: 0},
	{demoIntro: 0},
	{gametitle: 0},
	{hourglass: 0},
	{mainMenuBackground: 0},
	{soundoff: 0},
	{stars: 0},
	{transitionMask: 0},
	{teamNames: 0},
	{cupsWon: 0},
	{TextPS3: 0},
	{species: 0},
	{Timer: 0},
	{SpriteFontOLD: 0},
	{subClass: 0},
	{hudFont: 0},
	{lvlNumbers: 0},
	{panel: 0},
	{brojnaVrednost: 0},
	{mainText: 0},
	{prezName: 0},
	{textNaslov: 0},
	{klupska_boja_za_semafor: 0},
	{tutorialCounter: 0},
	{tutPointer: 0},
	{munja: 0},
	{Bullet: 0},
	{instBall: 0},
	{instGoal: 0},
	{instrPointer: 0},
	{LiteTween: 0},
	{instTargetRed: 0},
	{instKeeper: 0},
	{instPower: 0},
	{instPowerups: 0},
	{MrezaPS3: 0},
	{Gol_okvir: 0},
	{ZidPowerUp3D: 0},
	{stolice_gore: 0},
	{stolice_stepenice: 0},
	{dole_sivo: 0},
	{gore_sivo: 0},
	{banerTierTiled: 0},
	{banerWorldCupTiled: 0},
	{ogradaTiledBckg: 0},
	{zidTribineTiledBck: 0},
	{publika: 0},
	{stub_reflektora: 0},
	{obodKrova: 0},
	{bricksTiledBckg: 0},
	{cityTiledBck: 0},
	{ozgadaZicana: 0},
	{JedanRedPublikeTiled: 0},
	{publika_retka: 0},
	{tribina_donji_deo: 0},
	{zidPowerUpTiled: 0},
	{treesTiledBckg: 0},
	{zidTribineTiledBck3: 0},
	{"3DOkvirGola": 0},
	{"3dPublika": 0},
	{Reklame: 0},
	{TribinaZid: 0},
	{"3DKrovObod": 0},
	{"3dStubReflektora": 0},
	{"3DzicanaOgrada": 0},
	{"3DdaljaOkolina": 0},
	{KolskiUlaz: 0},
	{JedanRedPublike: 0},
	{"3D_tribina": 0},
	{"3DReflektor": 0},
	{Ground: 0},
	{ruf: 0},
	{ruf_sirotinjski: 0},
	{zidTribineTiledBck2: 0},
	{"3DLaznoNebo": 0},
	{cannonPlane3d: 0},
	{PlayerPS3: 0},
	{"8Direction": 0},
	{Car: 0},
	{PlayerProto: 0},
	{senka_igraca_na_tlu: 0},
	{ulogaIgraca: 0},
	{deltaZGolmana: 0},
	{deltaXGolmana: 0},
	{vremenskaZadrskaGolmana: 0},
	{desnjakIliLevak: 0},
	{bojaBroja: 0},
	{Player_v2: 0},
	{nodeID: 0},
	{deoTela: 0},
	{igracevID: 0},
	{m3DAttached: 0},
	{"3DObject": 0},
	{protokocka: 0},
	{Sprite: 0},
	{"3DShapeZaTestiranje": 0},
	{sutnuta: 0},
	{lopta: 0},
	{loptaSenka: 0},
	{TargetShutera3D: 0},
	{Velicina: 0},
	{indikatorSnage3D: 0},
	{pokazivacSnageSuta: 0},
	{TargetGolmana3D: 0},
	{"3DShape": 0},
	{senka_targeta_na_tlu: 0},
	{strelicaIndikator3D: 0},
	{IndikatorSnage3D_v2: 0},
	{"3DShape_GolMarker": 0},
	{power_indikator: 0},
	{timesNStarsArr: 0},
	{gameText: 0},
	{arrCup: 0},
	{arrCupTemp: 0},
	{teamsArr: 0},
	{arrKlubovi: 0},
	{arrTempKlubovi: 0},
	{arrAchievements: 0},
	{arrTiers: 0},
	{arrAchiReport: 0},
	{arrPowerUps: 0},
	{arrShutIshod: 0},
	{arrKlupskiIgraci: 0},
	{arrTemp: 0},
	{arrProtAvatariZaMec: 0},
	{arrNasiAvatariZaMec: 0},
	{arrNasiReprezentativci: 0},
	{arrAvatariTemp: 0},
	{arrCPUGolmanUcenje: 0},
	{arrFaktoriKosogHica: 0},
	{arrMinSnagaIDeltaX: 0},
	{arrP_i_FaktoriVremena: 0},
	{Elementi_stadiona: 0},
	{Razni3dShapeovi: 0},
	{RazniTiledObjekti: 0},
	{elementiInstrukcija: 0},
	{fiksniElemInstrukcija: 0},
	{DEMO_MOD: 0},
	{upravoResetovanaIgra: 0},
	{highResolutionOn: 0},
	{SHOW_INIT_PLAY_BUTTON: 0},
	{initCounter: 0},
	{ALL_MUTED: 0},
	{SKIP_INTRO: 0},
	{fajloviTela: 0},
	{fajloviKose: 0},
	{fajloviFacijalnihDlaka: 0},
	{klupske_boje: 0},
	{nazivSavedSlotConst: 0},
	{savedGameSlot: 0},
	{testTimeStampStari: 0},
	{testTimeStampNovi: 0},
	{razlikaTimeStampova: 0},
	{tempIndex: 0},
	{brojacMaterijala: 0},
	{nazivMaterijala: 0},
	{putanjaDoMaterijala: 0},
	{masaLopte: 0},
	{Ge: 0},
	{brojac: 0},
	{defaultLayoutWidth: 0},
	{defaultLayoutHeight: 0},
	{soundTagsList: 0},
	{soundFilesList: 0},
	{soundTag: 0},
	{soundVolume: 0},
	{soundLooping: 0},
	{ImageFrame: 0},
	{levelOfDifficulty: 0},
	{lastSelectedSize: 0},
	{LANGUAGE_ID: 0},
	{OLD_OR_NEW_GAME: 0},
	{SOUND_STATUS: 0},
	{MUSIC_STATUS: 0},
	{MYPLACE: 0},
	{LICENSING_PAGE: 0},
	{partnerURL: 0},
	{LINKS_ALLOWED: 0},
	{mecTekTrebaDaSeIgra: 0},
	{imeIgracevogTima: 0},
	{skracenicaIgracevogTima: 0},
	{rgbBoja: 0},
	{tipPruga: 0},
	{bojaOsnoveDresa: 0},
	{bojaPruga: 0},
	{bojaShortsa: 0},
	{imeIgracevogTimaZaMec: 0},
	{skracenicaIgracevogTimaZaMec: 0},
	{tipPrugaZaMec: 0},
	{bojaOsnoveDresaZaMec: 0},
	{bojaPrugaZaMec: 0},
	{bojaShortsaZaMec: 0},
	{brojNaDresu: 0},
	{bojaKoze: 0},
	{tipFrizure: 0},
	{bojaOsnoveDresaGolmana: 0},
	{bojaShortsaGolmana: 0},
	{bojaKozeGolmana: 0},
	{tipFrizureGolmana: 0},
	{imeProtivnickogTima: 0},
	{skracenicaProtivnickogTima: 0},
	{tipPrugaProtivnika: 0},
	{bojaOsnoveDresaProtivnika: 0},
	{bojaPrugaProtivnika: 0},
	{bojaShortsaProtivnika: 0},
	{brojNaDresuProtivnika: 0},
	{bojaKozeProtivnika: 0},
	{tipFrizureProtivnika: 0},
	{bojaOsnoveDresaProtivnickogGolmana: 0},
	{bojaShortsaProtivnickogGolmana: 0},
	{bojaKozeProtivnickogGolmana: 0},
	{tipFrizureProtivnickogGolmana: 0},
	{novac: 0},
	{dijamanti: 0},
	{trofejiTotal: 0},
	{gameMode: 0},
	{potrebanBrojUzastopnihDana: 0},
	{timeStampStari: 0},
	{timeStampNovi: 0},
	{danasSamProveravaoDatume: 0},
	{utakmicaRestartovana: 0},
	{nextLayoutName: 0},
	{previousLayoutName: 0},
	{powerUpID: 0},
	{prizeDiamonds: 0},
	{brojDijamanataZaAnimaciju: 0},
	{ciljX: 0},
	{ciljY: 0},
	{nextLayoutNameParam: 0},
	{numberToParse: 0},
	{total: 0},
	{razlikaUDanima: 0},
	{achiID: 0},
	{bonusGem: 0},
	{milliseconds: 0},
	{milliseconds2: 0},
	{part: 0},
	{num: 0},
	{uniPanelType: 0},
	{uniPanelXOffset: 0},
	{nazivTvina: 0},
	{buttonSubclass: 0},
	{Otpauziraj: 0},
	{tempIndex2: 0},
	{randomIndeksTela: 0},
	{randomIndeksKose: 0},
	{koseBelaca: 0},
	{koseCrnaca: 0},
	{randomIndeksFacDlake: 0},
	{facDlakeBelaca: 0},
	{facDlakeBelacaRidjih: 0},
	{facDlakeCrnaca: 0},
	{kojiTim: 0},
	{vrstaTima: 0},
	{rasa: 0},
	{SHOW_LEVEL_INTRO: 0},
	{SCROLLING_ALLOWED: 0},
	{SHOW_LEVEL_NUMBERS: 0},
	{RECTANGLE_POSITIONING_BUTTONS: 0},
	{SCROLLER_INITIAL_MOVE: 0},
	{levelSets: 0},
	{tierUnlocked: 0},
	{tiersNum: 0},
	{tierPicked: 0},
	{fiksnaSirina: 0},
	{fiksnaVisina: 0},
	{UCITAVANJE_THUMBOVA: 0},
	{poslednjiUcitan: 0},
	{thumbsXnum: 0},
	{xOffset: 0},
	{thumbsXnum2: 0},
	{thumbsYnum: 0},
	{xFactor: 0},
	{yFactor: 0},
	{fullWidth: 0},
	{tempString: 0},
	{tierID: 0},
	{buttonLevelParam: 0},
	{AFTER_AD_LAYOUT: 0},
	{crz_enabl: 0},
	{lgd_enabl: 0},
	{pki_enabl: 0},
	{gd_enabl: 0},
	{trenutakDolaskaNaAdLejaut: 0},
	{crz: 0},
	{jue: 0},
	{prev: 0},
	{mozeReklama: 0},
	{animationCounter: 0},
	{animationCounterSmall: 0},
	{lastMatchWon: 0},
	{playerMenuAnimations: 0},
	{potrebanBrojUtakmica: 0},
	{predloziTutorijal: 0},
	{anim: 0},
	{mojaReprezentacijaID: 0},
	{ulogaLok: 0},
	{putanjaDoBroja: 0},
	{putanjaDoBrojaFlip: 0},
	{igracID: 0},
	{imeTima: 0},
	{tipPrugaLok: 0},
	{bojaOsnoveDresaLok: 0},
	{bojaPrugaLok: 0},
	{bojaShortsaLok: 0},
	{brojNaDresuLok: 0},
	{indexIgracaUNizuAvatara: 0},
	{nasIgrac: 0},
	{materijalNormalnogBroja: 0},
	{materijalFlipovanogBroja: 0},
	{myTeamID: 0},
	{oppTeamID: 0},
	{teamsNum: 0},
	{arenaPicked: 0},
	{titlesWon: 0},
	{pickedTeamTitles: 0},
	{pickedID: 0},
	{orientation: 0},
	{numOfTitles: 0},
	{hostOrGuest: 0},
	{areWeIn: 0},
	{worldCupRound: 0},
	{numOfWorldCupRounds: 0},
	{pairsNum: 0},
	{pairs: 0},
	{startIndex: 0},
	{team1Ind: 0},
	{team2Ind: 0},
	{winnerID: 0},
	{weAreInTheCup: 0},
	{tempID: 0},
	{team1Strength: 0},
	{team2Strength: 0},
	{team1goals: 0},
	{team2goals: 0},
	{finalResult: 0},
	{winner: 0},
	{savesMade: 0},
	{pointsInThisGame: 0},
	{areWeHostsLocal: 0},
	{whoShoots: 0},
	{tempCupRound: 0},
	{tempResultCPU: 0},
	{tempResultPlayer: 0},
	{touched: 0},
	{entryFee: 0},
	{prize: 0},
	{privremeniPraviBrojTrofeja: 0},
	{idProtivnickogKluba: 0},
	{ciljX_: 0},
	{ciljY_: 0},
	{brojTimovaUTieru: 0},
	{pocetniID: 0},
	{totalMaxTrophies: 0},
	{tempCounter: 0},
	{tempPrize: 0},
	{imeTimaTemp: 0},
	{idBoje: 0},
	{iznosPromene: 0},
	{pickedUID: 0},
	{aktuelnaBoja: 0},
	{teamColorUID: 0},
	{brojAchievementa: 0},
	{brojSetovaAchievementa: 0},
	{offsetScroll: 0},
	{prviNeosvojeniAchi: 0},
	{brojOsvojenihAchija: 0},
	{tempText: 0},
	{indIndex: 0},
	{currentIndicatorID: 0},
	{desiredIndicatorID: 0},
	{touchedIndicatorID: 0},
	{teamEditorPage: 0},
	{brojImenaPoStrani: 0},
	{ponudjenoIme: 0},
	{randomNameID: 0},
	{vremenskaZadrska: 0},
	{trenutakAkcije: 0},
	{maxBrojStranaSaImenima: 0},
	{step: 0},
	{currentTouchX: 0},
	{idDugmetaSaImenom: 0},
	{textID: 0},
	{gemCena: 0},
	{instrStranica: 0},
	{vremePocetkaInstrukcije: 0},
	{brojacInstrukcije: 0},
	{maxBrojStranaSaInstrukcijama: 0},
	{tacnaStranica: 0},
	{maksBrojFazaInstrukcije: 0},
	{STATUS_AKCIJE: 0},
	{xPoc: 0},
	{yPoc: 0},
	{zPoc: 0},
	{scale: 0},
	{cameraDist: 0},
	{nivoStadiona: 0},
	{cenaRipleja: 0},
	{prviKrugSutiranja: 0},
	{learnTargetX1: 0},
	{learnTargetX2: 0},
	{learnTargetY1: 0},
	{learnTargetY2: 0},
	{guestShoots: 0},
	{tempFlag: 0},
	{gkpTargetX: 0},
	{gkpTargetY: 0},
	{gkpImpulse: 0},
	{isGoalScored: 0},
	{barTouched: 0},
	{netTouched: 0},
	{touchStarted: 0},
	{goalieStarted: 0},
	{cpuShootX: 0},
	{cpuShootY: 0},
	{shotNumber: 0},
	{indeksShutera: 0},
	{snagaProtivnika: 0},
	{igracPromasioSutUOvomMecu: 0},
	{igracOdbranioSutUOvomMecu: 0},
	{goalsScoredInThisMatch: 0},
	{stat_brOdigranihUtakmica: 0},
	{stat_uzastopneOdbraneUOvomMecu: 0},
	{stat_goloviUKarijeri: 0},
	{stat_pobedeUKarijeri: 0},
	{stat_brojUzastopnihDanaIgranja: 0},
	{shuterSeSprema: 0},
	{golmanSeSprema: 0},
	{golmanSeBaca: 0},
	{prikaziTutorijalShutera: 0},
	{prikaziTutorijalGolmana: 0},
	{tutorijalBrojac: 0},
	{golmanoveAnimacije: 0},
	{xT: 0},
	{yT: 0},
	{zT: 0},
	{factor: 0},
	{zglobovi: 0},
	{vremeUTrenutkuSuta: 0},
	{vremeUTrenutkuProlaskaKrozTarget: 0},
	{loopindexJS: 0},
	{startXTutorijalPanela: 0},
	{golmanskeIdleAnimacije: 0},
	{shuterskeIdleAnimacije: 0},
	{vrstaSuta: 0},
	{nazivOsnovneBojeDresa: 0},
	{definicijaBoje: 0},
	{golZvuk: 0},
	{zvukGolaID: 0},
	{ko: 0},
	{promasajZvuk: 0},
	{zvukPromasajaID: 0},
	{preostaloSutevaIgracu: 0},
	{preostaloSutevaCPUu: 0},
	{maksPreostalihSuteva: 0},
	{tempResultPlayerLoc: 0},
	{tempResultCPULoc: 0},
	{idPowerUpa: 0},
	{xZida: 0},
	{tutorijal: 0},
	{zeljenoXTargeta: 0},
	{zeljenoZTargeta: 0},
	{zeljenoXMin: 0},
	{zeljenoXMax: 0},
	{zeljenoZMax: 0},
	{brojPeriodaCekanja: 0},
	{maksX: 0},
	{maksZ: 0},
	{minX: 0},
	{cekanjeNaPrikazTargeta: 0},
	{vremeReakcijeCPUGolmana: 0},
	{randomDecisionNum: 0},
	{maxX: 0},
	{maxZ: 0},
	{testLokalnaPromenljiva: 0},
	{x1: 0},
	{x2: 0},
	{z1: 0},
	{z2: 0},
	{wid: 0},
	{pomerajZElevacije: 0},
	{deltaXvece: 0},
	{deltaXmanje: 0},
	{relPomerajDeltaX: 0},
	{relPomerajElevacije: 0},
	{elevacijaManja: 0},
	{elevacijaVeca: 0},
	{vreme1: 0},
	{vreme2: 0},
	{vremeRez: 0},
	{iManje: 0},
	{iVece: 0},
	{jManje: 0},
	{jVece: 0},
	{D: 0},
	{apsDeltaX: 0},
	{intervencijaID: 0},
	{intervencijaSekundarnaID: 0},
	{razlikaXTargetVsGolman: 0},
	{vremenskaKompenzacijaAnimacije: 0},
	{faktorDT: 0},
	{KorakKlizanjaGolmana: 0},
	{frejmShuta: 0},
	{bodyVrsta: 0},
	{Alfa: 0},
	{Beta: 0},
	{S: 0},
	{V0: 0},
	{faktorV: 0},
	{faktorZ: 0},
	{impulsX: 0},
	{impulsY: 0},
	{impulsZ: 0},
	{zTarg: 0},
	{A1: 0},
	{A2: 0},
	{A3: 0},
	{B1: 0},
	{B2: 0},
	{B3: 0},
	{C1: 0},
	{C2: 0},
	{C3: 0},
	{pomerajSnage: 0},
	{minRezultat: 0},
	{optimalniUgao: 0},
	{trenutniAlpha: 0},
	{trenutniRezultat: 0},
	{prethodniRezultat: 0},
	{faktorDuzine: 0},
	{faktorBrzine: 0},
	{grav: 0},
	{extraTezina: 0},
	{nivoiStadionaToken: 0},
	{atmosferaNaStadionuZvuk: 0},
	{"3dTribineVisine": 0},
	{ZElevElemenataKorekcija: 0},
	{RufSirotiZElev: 0},
	{YKorekcija: 0},
	{CameraZ: 0},
	{LookAtZ: 0},
	{powerUpIndex: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	ButtonPS3: class extends self.IButtonInstance {},
	_3DCamera: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	SVGPicture: class extends self.ISVGPictureInstance {},
	teamPickButton: class extends self.ISpriteInstance {},
	zvezdicazalogo: class extends self.ISpriteInstance {},
	teamLogo: class extends self.ISpriteInstance {},
	strength: class extends self.ISpriteInstance {},
	PrevLevel: class extends self.IButtonInstance {},
	NextLevel: class extends self.IButtonInstance {},
	TestDugme: class extends self.IButtonInstance {},
	button: class extends self.ISpriteInstance {},
	levelButton: class extends self.ISpriteInstance {},
	myLogo: class extends self.ISpriteInstance {},
	partnerLogo: class extends self.ISpriteInstance {},
	teamColor: class extends self.ISpriteInstance {},
	krila_buttonLevel: class extends self.ISpriteInstance {},
	podloga_za_broj: class extends self.ISpriteInstance {},
	cupBranchPivot: class extends self.ISpriteInstance {},
	teamLogoCupBranch: class extends self.ISpriteInstance {},
	cupTree: class extends self.ISpriteInstance {},
	kup: class extends self.ISpriteInstance {},
	kup2: class extends self.ISpriteInstance {},
	lovor: class extends self.ISpriteInstance {},
	teamLogoZraci: class extends self.ISpriteInstance {},
	levelButtonStarMap: class extends self.ISpriteInstance {},
	levelIntroImage: class extends self.ISpriteInstance {},
	thumbFrame: class extends self.ISpriteInstance {},
	page_indicator: class extends self.ISpriteInstance {},
	uniThumb: class extends self.ISpriteInstance {},
	scroller: class extends self.ISpriteInstance {},
	maskAchievements: class extends self.ITiledBackgroundInstance {},
	gemParticles: class extends self.IParticlesInstance {},
	pausePanel: class extends self.ISpriteInstance {},
	uniPanel: class extends self.ISpriteInstance {},
	demoIntro: class extends self.ISpriteInstance {},
	gametitle: class extends self.ISpriteInstance {},
	hourglass: class extends self.ISpriteInstance {},
	mainMenuBackground: class extends self.ISpriteInstance {},
	soundoff: class extends self.ISpriteInstance {},
	stars: class extends self.ISpriteInstance {},
	transitionMask: class extends self.ISpriteInstance {},
	teamNames: class extends self.ITextInstance {},
	cupsWon: class extends self.ITextInstance {},
	TextPS3: class extends self.ITextInstance {},
	SpriteFontOLD: class extends self.ISpriteFontInstance {},
	hudFont: class extends self.ISpriteFontInstance {},
	lvlNumbers: class extends self.ITextInstance {},
	mainText: class extends self.ITextInstance {},
	prezName: class extends self.ITextInstance {},
	textNaslov: class extends self.ITextInstance {},
	klupska_boja_za_semafor: class extends self.ISpriteInstance {},
	tutPointer: class extends self.ISpriteInstance {},
	munja: class extends self.ISpriteInstance {},
	instBall: class extends self.ISpriteInstance {},
	instGoal: class extends self.ISpriteInstance {},
	instrPointer: class extends self.ISpriteInstance {},
	instTargetRed: class extends self.ISpriteInstance {},
	instKeeper: class extends self.ISpriteInstance {},
	instPower: class extends self.ISpriteInstance {},
	instPowerups: class extends self.ISpriteInstance {},
	MrezaPS3: class extends self.I3DShapeInstance {},
	Gol_okvir: class extends self.IWorldInstance {},
	ZidPowerUp3D: class extends self.I3DShapeInstance {},
	stolice_gore: class extends self.ITiledBackgroundInstance {},
	stolice_stepenice: class extends self.ITiledBackgroundInstance {},
	dole_sivo: class extends self.ITiledBackgroundInstance {},
	gore_sivo: class extends self.ITiledBackgroundInstance {},
	banerTierTiled: class extends self.ITiledBackgroundInstance {},
	banerWorldCupTiled: class extends self.ITiledBackgroundInstance {},
	ogradaTiledBckg: class extends self.ITiledBackgroundInstance {},
	zidTribineTiledBck: class extends self.ITiledBackgroundInstance {},
	publika: class extends self.ITiledBackgroundInstance {},
	stub_reflektora: class extends self.ITiledBackgroundInstance {},
	obodKrova: class extends self.ITiledBackgroundInstance {},
	bricksTiledBckg: class extends self.ITiledBackgroundInstance {},
	cityTiledBck: class extends self.ITiledBackgroundInstance {},
	ozgadaZicana: class extends self.ITiledBackgroundInstance {},
	JedanRedPublikeTiled: class extends self.ITiledBackgroundInstance {},
	publika_retka: class extends self.ITiledBackgroundInstance {},
	tribina_donji_deo: class extends self.ITiledBackgroundInstance {},
	zidPowerUpTiled: class extends self.ITiledBackgroundInstance {},
	treesTiledBckg: class extends self.ITiledBackgroundInstance {},
	zidTribineTiledBck3: class extends self.ITiledBackgroundInstance {},
	_3DOkvirGola: class extends self.I3DShapeInstance {},
	_3dPublika: class extends self.I3DShapeInstance {},
	Reklame: class extends self.I3DShapeInstance {},
	TribinaZid: class extends self.I3DShapeInstance {},
	_3DKrovObod: class extends self.I3DShapeInstance {},
	_3dStubReflektora: class extends self.I3DShapeInstance {},
	_3DzicanaOgrada: class extends self.I3DShapeInstance {},
	_3DdaljaOkolina: class extends self.I3DShapeInstance {},
	KolskiUlaz: class extends self.I3DShapeInstance {},
	JedanRedPublike: class extends self.I3DShapeInstance {},
	_3D_tribina: class extends self.I3DShapeInstance {},
	_3DReflektor: class extends self.I3DShapeInstance {},
	Ground: class extends self.ISpriteInstance {},
	ruf: class extends self.ISpriteInstance {},
	ruf_sirotinjski: class extends self.ISpriteInstance {},
	zidTribineTiledBck2: class extends self.ITiledBackgroundInstance {},
	_3DLaznoNebo: class extends self.I3DShapeInstance {},
	cannonPlane3d: class extends self.IWorldInstance {},
	PlayerPS3: class extends self.IWorldInstance {},
	PlayerProto: class extends self.ISpriteInstance {},
	senka_igraca_na_tlu: class extends self.ISpriteInstance {},
	Player_v2: class extends self.IWorldInstance {},
	m3DAttached: class extends self.I3DShapeInstance {},
	_3DObject: class extends self.IWorldInstance {},
	protokocka: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_3DShapeZaTestiranje: class extends self.I3DShapeInstance {},
	lopta: class extends self.IWorldInstance {},
	loptaSenka: class extends self.ISpriteInstance {},
	TargetShutera3D: class extends self.I3DShapeInstance {},
	indikatorSnage3D: class extends self.I3DShapeInstance {},
	pokazivacSnageSuta: class extends self.ISpriteInstance {},
	TargetGolmana3D: class extends self.I3DShapeInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	senka_targeta_na_tlu: class extends self.ISpriteInstance {},
	strelicaIndikator3D: class extends self.I3DShapeInstance {},
	IndikatorSnage3D_v2: class extends self.I3DShapeInstance {},
	_3DShape_GolMarker: class extends self.I3DShapeInstance {},
	power_indikator: class extends self.ISpriteInstance {},
	timesNStarsArr: class extends self.IArrayInstance {},
	gameText: class extends self.IArrayInstance {},
	arrCup: class extends self.IArrayInstance {},
	arrCupTemp: class extends self.IArrayInstance {},
	teamsArr: class extends self.IArrayInstance {},
	arrKlubovi: class extends self.IArrayInstance {},
	arrTempKlubovi: class extends self.IArrayInstance {},
	arrAchievements: class extends self.IArrayInstance {},
	arrTiers: class extends self.IArrayInstance {},
	arrAchiReport: class extends self.IArrayInstance {},
	arrPowerUps: class extends self.IArrayInstance {},
	arrShutIshod: class extends self.IArrayInstance {},
	arrKlupskiIgraci: class extends self.IArrayInstance {},
	arrTemp: class extends self.IArrayInstance {},
	arrProtAvatariZaMec: class extends self.IArrayInstance {},
	arrNasiAvatariZaMec: class extends self.IArrayInstance {},
	arrNasiReprezentativci: class extends self.IArrayInstance {},
	arrAvatariTemp: class extends self.IArrayInstance {},
	arrCPUGolmanUcenje: class extends self.IArrayInstance {},
	arrFaktoriKosogHica: class extends self.IArrayInstance {},
	arrMinSnagaIDeltaX: class extends self.IArrayInstance {},
	arrP_i_FaktoriVremena: class extends self.IArrayInstance {},
	Elementi_stadiona: class extends self.I3DShapeInstance {},
	Razni3dShapeovi: class extends self.I3DShapeInstance {},
	RazniTiledObjekti: class extends self.ITiledBackgroundInstance {},
	elementiInstrukcija: class extends self.ISpriteInstance {},
	fiksniElemInstrukcija: class extends self.ISpriteInstance {}
}